import { Link } from "react-router";
import { AtlasLogo } from "./Nav";
import { Sparkles } from "lucide-react";
import { IS_STATIC_DEMO } from "@/lib/staticDemo";

export function AIBadge({ label = "Atlas AI" }: { label?: string }) {
  return (
    <span className="chip border border-white/60 bg-white/70 text-foreground/70 backdrop-blur">
      <Sparkles className="h-3 w-3 text-[hsl(var(--atlas-lavender))]" />
      {label}
    </span>
  );
}

export default function Footer() {
  return (
    <footer className="relative z-10 mt-24 px-4 pb-10 sm:px-6">
      <div className="glass mx-auto max-w-6xl rounded-atlas-lg p-8 sm:p-10">
        <div className="flex flex-col items-start justify-between gap-8 md:flex-row md:items-center">
          <div>
            <AtlasLogo />
            <p className="mt-3 max-w-sm text-sm leading-relaxed text-muted-foreground">
              Discover, experience and remember the world — through authentic
              first-person journeys, captured on Atlas glasses and retold by Atlas AI.
            </p>
          </div>
          <div className="grid grid-cols-2 gap-x-16 gap-y-3 text-sm">
            <FooterCol
              title="Product"
              links={[
                { to: "/glasses", label: "Atlas Lens" },
                { to: "/planner", label: "AI Planner" },
                { to: "/create", label: "AI Studio" },
              ]}
            />
            <FooterCol
              title="Community"
              links={[
                { to: "/explore", label: "Journeys" },
                { to: "/dna", label: "Travel DNA" },
                { to: "/", label: "About" },
              ]}
            />
          </div>
        </div>
        <div className="mt-8 flex flex-col items-start justify-between gap-3 border-t border-foreground/5 pt-6 text-xs text-muted-foreground sm:flex-row sm:items-center">
          <p>© 2026 Atlas — an AR + AI travel ecosystem concept.</p>
          <p className="inline-flex items-center gap-1.5">
            <Sparkles className="h-3 w-3 text-[hsl(var(--atlas-lavender))]" />
            {IS_STATIC_DEMO
              ? "Read-only demo — interactive features require the Atlas backend"
              : "Films, banners, stories and narration generated by AI models"}
          </p>
        </div>
      </div>
    </footer>
  );
}

function FooterCol({
  title,
  links,
}: {
  title: string;
  links: { to: string; label: string }[];
}) {
  return (
    <div className="space-y-2.5">
      <p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{title}</p>
      {links.map((l) => (
        <Link key={l.label} to={l.to} className="block font-semibold text-foreground/70 transition-colors hover:text-foreground">
          {l.label}
        </Link>
      ))}
    </div>
  );
}
